trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:

# Lint the Bicep file.
- stage: Lint
  jobs: 
  - template: pipeline-templates/lint.yml

- stage: StagingPreflightValidation
  jobs:
  - template: pipeline-templates/preflight-validation.yml
    parameters:
      environment: staging
      serviceConnectionName: bicep-apim-service-connection

- stage: StagingDeploy
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      environment: staging
      serviceConnectionName: bicep-apim-service-connection

- stage: ProductionPreflightValidation
  jobs:
  - template: pipeline-templates/preflight-validation.yml
    parameters:
      environment: prod
      serviceConnectionName: bicep-apim-service-connection

- stage: ProductionDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      environment: prod
      serviceConnectionName: bicep-apim-service-connection