trigger:
  batch: true
  branches:
    include:
    - staging

pool:
  vmImage: ubuntu-latest

stages:

# Lint the Bicep file.
- stage: Lint
  jobs: 
  - template: pipeline-templates/lint.yml

- stage: PreflightValidationDev
  jobs:
  - template: pipeline-templates/preflight-validation.yml
    parameters:
      environment: dev
      serviceConnectionName: bicep-apim-service-connection

- stage: DevDeploy
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      environment: dev
      serviceConnectionName: bicep-apim-service-connection

- stage: StagingPreflightValidation
  jobs:
  - template: pipeline-templates/preflight-validation.yml
    parameters:
      environment: staging
      serviceConnectionName: bicep-apim-service-connection

- stage: StagingDeploy
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'staging'))
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      environment: staging
      serviceConnectionName: bicep-apim-service-connection