parameters:
- name: mainBicepFile
  type: string
  default: ./main.bicep

jobs:
- job: LintCode
  displayName: Lint code
  steps:
    - script: |
        az bicep build --file ${{parameters.mainBicepFile}}
      name: LintBicepCode
      displayName: Run Bicep linter