parameters:
- name: environment
  type: string
- name: mainBicepFile
  type: string
  default: ./main.bicep
- name: serviceConnectionName
  type: string
- name: location
  type: string
  default: eastus

jobs:
- job: PreflightValidation_${{parameters.environment}}
  displayName: Preflight Validation
  variables:
  - group: PUBLISHER_DETAILS
  steps:
    - task: AzureCLI@2
      name: RunPreflightValidation
      displayName: RunPreflightValidation
      inputs:
        azureSubscription: ${{parameters.serviceConnectionName}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub validate \
          --template-file ${{parameters.mainBicepFile}} \
          --name ${{parameters.environment}}-$(Build.BuildNumber)-validation \
          --location ${{parameters.location}} \
          --parameters ${{parameters.environment}}.parameters.json \
                        publisherName=$(publisherName) \
                        publisherEmail=$(publisherEmail)
