name: bicep-workflow

on: [workflow_dispatch]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      mainBicepFile: ./main.bicep 
      
  validate:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Setup local params file with secret
    - name: Create Local Params
      env:
        PARAM_FILE: ${{ secrets.DEPLOY_PARAMETERS }}
      run: |
        echo creating local.parameters.json for the run
        echo $PARAM_FILE > local.parameters.json
    
    # This step does 'preflight validation' with ARM - check valid names, regions, etc.
    - name: Preflight Validation
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        scope: subscription
        failOnStdErr: false
        deploymentMode: Validate
        region: eastus
        template: main.bicep
        parameters: local.parameters.json
    
  deploy:
    runs-on: ubuntu-latest
    needs: [lint,validate]
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: create local param file
      env:
        PARAM_FILE: ${{ secrets.DEPLOY_PARAMETERS }}
      run: |
        echo creating local.parameters.json for the run
        echo $PARAM_FILE > local.parameters.json
        
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        scope: subscription
        failOnStdErr: false
        region: eastus
        template: main.bicep
        parameters: local.parameters.json
        
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Run Test Against APIM
      run: echo TESTING

  # rollback:
  #   runs-on: ubuntu-latest
  #   needs: test
