name: bicep-workflow

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        template: ./main.bicep
        parameters: ${{ secrets.DEPLOY_PARAMETERS }}
