name: bicep-workflow

on: [workflow_dispatch, push]

# https://github.com/actions/runner/issues/480
# cannot use directly in reusable workflows
env:
  REGION: eastus
  SCOPE: subscription

jobs:

  lint:
    uses: ./.github/workflows/lint.yml
    # with:
    #   mainBicepFile: ./main.bicep 
      
  preflight-validation-dev:
    uses: ./.github/workflows/preflight-validation.yml
    needs: lint
    with:
      mainBicepFile: ./main.bicep
      environment: Development
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
    
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    needs: preflight-validation-dev
    with:
      environment: Development
      mainBicepFile: ./main.bicep
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DEPLOY_PARAMETERS: ${{ secrets.DEPLOY_PARAMETERS }}
 
  # test:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #   - name: Run Test Against APIM
  #     run: echo TESTING

  # rollback:
  #   runs-on: ubuntu-latest
  #   needs: test
