name: bicep-workflow

on:

  push:
    branches:
      - staging

# https://github.com/actions/runner/issues/480
# cannot use directly in reusable workflows
env:
  REGION: eastus
  SCOPE: subscription

jobs:

  lint:
    uses: ./.github/workflows/lint.yml

  preflight-validation-staging:
    uses: ./.github/workflows/preflight-validation.yml
    needs: lint
    with:
      environment: staging
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}

  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    needs: preflight-validation-dev
    with:
      environment: staging
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
 
  # test:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #   - name: Run Test Against APIM
  #     run: echo TESTING

  # rollback:
  #   runs-on: ubuntu-latest
  #   needs: test